variable "appId" {}
variable "password" {}
variable "cluster-rg-name" {}
variable "location" {}
variable "aks-network-name" {}
variable "aks-subnet-name" {}
variable "server-name" {}
variable "administrator_login" {}
variable "administrator_login_password" {}
variable "sku_name" {}
variable "public_network_access_enabled" {}
variable "webapp-db-name" {}
variable "poller-db-name" {}
variable "notifier-db-name" {}
variable "aks-cluster-name" {}
variable "node-rg-name" {}
variable "dns_prefix" {}
variable "private_cluster_enabled" {}
variable "min_count" {}
variable "max_count" {}
variable "node_count" {}
variable "public_key" {}
variable "vm_size" {}
variable "dns_zone" {}
variable "key_path" {}
